### ISSUE TITLE
span class

### ISSUE THREAD

**Issue by mikebutts** [LCrandall1/prj-rev-bwfs-dasmoto#1]
https://github.com/LCrandall1/prj-rev-bwfs-dasmoto/blob/f10979396c023cd3adfde844b56848a1ae4ed729/DasmotosArtsCrafts/index.html#L16

Good job on this, not many get this on the first project, some use strong tags or put styling on the element itself, span class is the proper way.

**Comment by LCrandall1** [comment]
Thanks Mike!
